config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :products do
    member do
      get :new_movement
      post :create_movement
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :product
  MovementTypes = {add: 0, remove: 1}
  validates :quantity, presence: true, numericality: true

  def self.get_movement_types
    {
      'Agregar' => MovementTypes[:add],
      'Quitar' => MovementTypes[:remove]
    }
  end

  def movement_type_name
    return 'Agregar' if movement_type == MovementTypes[:add]
    return 'Quitar' if movement_type == MovementTypes[:remove]
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :movements
    validates :name, presence: true

    def quantity
        total = 0
        self.movements.each do|movement|
            if movement.movement_type == Movement::MovementTypes[:add]
                total += movement.quantity
            else
                total -= movement.quantity
            end
        end
        return total
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def new_movement
    @product = Product.find(params[:id])
    @movement = Movement.new
  end

  def create_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(movements_params)
    @movement.product_id = @product.id
    if @movement.save
      redirect_to @product, notice: 'Se creo el movimiento correctamente'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el movimiento'
      render :new_movement, status: :unprocessable_entity
    end
  end

  private

    def movements_params
      params.require(:movement).permit(:quantity, :movement_type, :coment)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :reference, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/index.html.erb
<div class="row">
    <div class="col-lg-6">
        <div class="card p-5">
            <h2>Ultimos movimientos:</h2>
            <table class="table mt-4">
                <thead>
                    <tr>
                    <th>ID:</th>
                    <th>Nombre:</th>
                    <th>Referencia:</th>
                    <th>Cantidad:</th>
                    </tr>
                    <tbody>
                    <% @products.each do |product| %>
                        <tr>
                        <td><%= product.id %></td>
                        <td><%= product.name %></td>
                        <td><%= product.reference %></td>
                        <td><%= product.quantity %></td>
                        </tr>
                    <% end %>
                    </tbody>
                </thead>
            </table>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card p-5">
            <h2>Top productos:</h2>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cellar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "sb-admin-2.min", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "all.min", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-truck"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Cellar App</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="<%= root_path %>">
                    <i class="fas fa-tasks fa-fw"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<%= products_path %>" >
                    <i class="fas fa-wallet fa-fw "></i>
                    <span>Productos</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <!-- Nav Item - Alerts -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bell fa-fw"></i>
                                <!-- Counter - Alerts -->
                                <span class="badge badge-danger badge-counter">3+</span>
                            </a>

                        <!-- Nav Item - Messages -->
                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-envelope fa-fw"></i>
                                <!-- Counter - Messages -->
                                <span class="badge badge-danger badge-counter">7</span>
                            </a>


                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Admin</span>
                                <i class="fas fa-user"></i>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                      <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy;Nicolas Valbuena</span>
                    </div>
                </div>
            </footer>
        </div>
    </div>



    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>
</body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with(model: product) do |form| %>
        <% if product.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
              <% product.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :reference, style: "display: block" %>
          <%= form.text_field :reference, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :description, style: "display: block" %>
          <%= form.text_area :description, class:"form-control" %>
        </div>

        <div>
          <%= form.submit "agregar", class:"btn btn-primary mt-3 col-1 " %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Reference:</strong>
    <%= product.reference %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editar producto:</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Ver detalles del producto", @product, class:"btn btn-primary" %> |
  <%= link_to "Regresar a productos", products_path, class:"btn btn-warning" %>
</div>

app/views/products/index.html.erb
<h1>Lista de productos</h1>
<a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
    <i class='fas fa-flag'></i>
  </span>
  <span class="text">Crear Producto</span>
<a/>

<a href="<%= products_path(format: :xlsx) %>" class="btn btn-success btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-file"></i>
  </span>
  <span class="text">Exportar a Excel</span>
</a>

<table class="table mt-4">
  <thead>
    <tr>
      <th>ID:</th>
      <th>Nombre:</th>
      <th>Referencia:</th>
      <th>Cantidad:</th>
      <th>Acciones:</th>
    </tr>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.name %></td>
          <td><%= product.reference %></td>
          <td><%= product.quantity %></td>
          <td><%= link_to "Detalles", product_path(product), class:"btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </thead>
</table>

app/views/products/new.html.erb
<h1>Crear nuevo producto:</h1>
<div>
  <%= link_to "Regresar al listado de productos", products_path, class:"btn btn-primary mb-4" %>
</div>
 
<%= render "form", product: @product %>

 

app/views/products/new_movement.html.erb
<h1>Crear movimiento</h1>
<div class="row">
    <div class="col-lg-12">
        <div class="card">  
            <table class="table">
                <tr>
                    <td><b>Nombre:</b></td>
                    <td> <%=@product.name%> </td>
                </tr>
                <tr>
                    <td><b>Referencia:</b></td>
                    <td> <%=@product.reference%></td>
                </tr>
            </table>
        </div>
    </div>
</div>

  <div class="row">
    <div class="col-lg-12"> 
      <div class="card p-5">
        <%= form_with model: @movement, url: create_movement_product_path(@product) do |f| %>

        <% if @movement.errors.any? %>
            <div class="alert alert-danger">
                <h4><%= flash[:notice] %></h4>
                <ul>
                    <% @movement.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
        

        <div class="form-group">  
            <%= f.label :movement_type, "Tipo de movimiento" %>
            <%= f.select :movement_type, options_for_select(Movement.get_movement_types),{}, class:'form-control col-2' %>
        </div>

        <div class="form-group">  
            <%= f.label :quantity, "Cantidad" %>
            <%= f.number_field :quantity, class:'form-control col-2' %>
        </div>
        <div class="form-group">  
            <%= f.label :coment, "Comentario" %>
            <%= f.text_area :coment, class:'form-control col-8' %>
        </div>
        <div class="form-group">    
            <%= f.submit 'Crear movimiento', class:'btn btn-primary' %>
            <%= link_to 'Cancelar', product_path(@product), class:'btn btn-danger' %>
        </div>

        <% end %>
      </div>
    </div>
  </div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del producto:</h1>
    <%= link_to"Regresar al listado", products_path, class:"btn btn-primary col-2 p-2" %>
    <%= link_to"Editar este producto", edit_product_path(@product), class:"btn btn-primary col-2 p-2" %>
    <%= link_to"Eliminar este producto",@product, method: :delete, class:"btn btn-danger col-2 p-2" %> 
    <%= link_to"Crear movimiento", new_movement_product_path(@product), class:"btn btn-success col-2 p-2" %>  
  </div>

  <div class="card mt-3 col-lg-6">
    <table class="table">
      <tr>
        <td><b>Nombre del producto:</b></td>
        <td> <%= @product.name%> </td>
      </tr>
      <tr>
        <td><b>Referencia:</b></td>
        <td> <%= @product.reference%></td>
      </tr>
      <tr>
        <td><b>Descripción:</b></td>
        <td> <%= @product.description%></td>
      </tr>
      <tr>
        <td><b>Cantidad Actual:</b></td>
        <td> <%= @product.quantity%></td>
      </tr>
      <tr>
        <td><b>Fecha de creacion:</b></td>
        <td> <%= @product.created_at %></td>
      </tr>
    </table>
  </div>
</div>


 <div class="row mt-4">
  <div class="col-lg-12 "> 
    <div class="card p-2">
      <h1>Movimientos:</h1>
      <table class="table">
        <thead> 
          <tr>
            <th>Tipo:</th>
            <th>Cantidad:</th>
            <th>Comentario:</th>
            <th>Fecha/hora</th>
          </tr>
        </thead>
        <tbody>
          <% @product.movements.each do |movement|%>
            <tr>
              <td><%= movement.movement_type_name%></td>
              <td><%= movement.quantity%></td>
              <td><%= movement.coment%></td>
              <td><%= movement.created_at%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
 </div>